version: "3.9"
services:
  codecoho-db:
    image: postgres
    restart: always
    container_name: codecoho-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: